---
swagger: "2.0"
info:
  description: ""
  version: ""
  title: "User Data API"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
- "https"
- "http"
security:
- APIKeyHeader: []
paths:
  /healthcheck:
    get:
      tags:
      - "user_data"
      description: "Get the status of the service."
      operationId: "healthcheck"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "The service is operating normally."
          schema:
            $ref: "#/definitions/health_info"
      security: []
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /adminnotes:
    get:
      tags:
      - "user_data"
      operationId: "adminnote_list"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "An optional query parameter specifying the offset in the result\
          \ set to start from."
        required: false
        type: "integer"
        default: 0
        minimum: 0
      - name: "limit"
        in: "query"
        description: "An optional query parameter to limit the number of results returned."
        required: false
        type: "integer"
        default: 20
        maximum: 100
        minimum: 1
      - name: "user_id"
        in: "query"
        description: "An optional query parameter to filter by user_id"
        required: false
        type: "string"
        format: "uuid"
      - name: "creator_id"
        in: "query"
        description: "An optional query parameter to filter by creator (a user_id)"
        required: false
        type: "string"
        format: "uuid"
      - name: "admin_note_ids"
        in: "query"
        description: "An optional list of adminnote ids"
        required: false
        type: "array"
        items:
          type: "integer"
        collectionFormat: "multi"
        minItems: 0
        uniqueItems: true
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/admin_note"
          headers:
            X-Total-Count:
              type: "integer"
              description: "The total number of results matching the query"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    post:
      tags:
      - "user_data"
      operationId: "adminnote_create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/admin_note_create"
      responses:
        201:
          description: ""
          schema:
            $ref: "#/definitions/admin_note"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /adminnotes/{admin_note_id}:
    get:
      tags:
      - "user_data"
      operationId: "adminnote_read"
      produces:
      - "application/json"
      parameters:
      - name: "admin_note_id"
        in: "path"
        description: "A unique integer value identifying the admin note."
        required: true
        type: "integer"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/admin_note"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    put:
      tags:
      - "user_data"
      operationId: "adminnote_update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "admin_note_id"
        in: "path"
        description: "A unique integer value identifying the admin note."
        required: true
        type: "integer"
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/admin_note_update"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/admin_note"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    delete:
      tags:
      - "user_data"
      operationId: "adminnote_delete"
      parameters:
      - name: "admin_note_id"
        in: "path"
        description: "A unique integer value identifying the admin note."
        required: true
        type: "integer"
      responses:
        204:
          description: "Deleted"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /sitedataschemas:
    get:
      tags:
      - "user_data"
      operationId: "sitedataschema_list"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "An optional query parameter specifying the offset in the result\
          \ set to start from."
        required: false
        type: "integer"
        default: 0
        minimum: 0
      - name: "limit"
        in: "query"
        description: "An optional query parameter to limit the number of results returned."
        required: false
        type: "integer"
        default: 20
        maximum: 100
        minimum: 1
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/site_data_schema"
          headers:
            X-Total-Count:
              type: "integer"
              description: "The total number of results matching the query"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    post:
      tags:
      - "user_data"
      operationId: "sitedataschema_create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/site_data_schema_create"
      responses:
        201:
          description: ""
          schema:
            $ref: "#/definitions/site_data_schema"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /sitedataschemas/{site_id}:
    get:
      tags:
      - "user_data"
      operationId: "sitedataschema_read"
      produces:
      - "application/json"
      parameters:
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/site_data_schema"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    put:
      tags:
      - "user_data"
      operationId: "sitedataschema_update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/site_data_schema_update"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/site_data_schema"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    delete:
      tags:
      - "user_data"
      operationId: "sitedataschema_delete"
      parameters:
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      responses:
        204:
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /usersitedata:
    get:
      tags:
      - "user_data"
      operationId: "usersitedata_list"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "An optional query parameter specifying the offset in the result\
          \ set to start from."
        required: false
        type: "integer"
        default: 0
        minimum: 0
      - name: "limit"
        in: "query"
        description: "An optional query parameter to limit the number of results returned."
        required: false
        type: "integer"
        default: 20
        maximum: 100
        minimum: 1
      - name: "user_id"
        in: "query"
        description: "An optional query parameter to filter by user_id"
        required: false
        type: "string"
        format: "uuid"
      - name: "site_id"
        in: "query"
        description: "An optional query parameter to filter by site_id"
        required: false
        type: "integer"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user_site_data"
          headers:
            X-Total-Count:
              type: "integer"
              description: "The total number of results matching the query"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    post:
      tags:
      - "user_data"
      operationId: "usersitedata_create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/user_site_data_create"
      responses:
        201:
          description: ""
          schema:
            $ref: "#/definitions/user_site_data"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /usersitedata/{user_id}/{site_id}:
    get:
      tags:
      - "user_data"
      operationId: "usersitedata_read"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/user_site_data"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    put:
      tags:
      - "user_data"
      operationId: "usersitedata_update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/user_site_data_update"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/user_site_data"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    delete:
      tags:
      - "user_data"
      operationId: "usersitedata_delete"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      responses:
        204:
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /deleteduser:
    get:
      tags:
      - "user_data"
      operationId: "deleteduser_list"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "An optional query parameter specifying the offset in the result\
          \ set to start from."
        required: false
        type: "integer"
        default: 0
        minimum: 0
      - name: "limit"
        in: "query"
        description: "An optional query parameter to limit the number of results returned."
        required: false
        type: "integer"
        default: 20
        maximum: 100
        minimum: 1
      - name: "deleter_id"
        in: "query"
        description: "An optional query parameter to filter by deleter_id"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/deleted_user"
          headers:
            X-Total-Count:
              type: "integer"
              description: "The total number of results matching the query"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    post:
      tags:
      - "user_data"
      operationId: "deleteduser_create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/deleted_user_create"
      responses:
        201:
          description: ""
          schema:
            $ref: "#/definitions/deleted_user"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /deleteduser/{user_id}:
    get:
      tags:
      - "user_data"
      operationId: "deleteduser_read"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/deleted_user"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    put:
      tags:
      - "user_data"
      operationId: "deleteduser_update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/deleted_user_update"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/deleted_user"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    delete:
      tags:
      - "user_data"
      operationId: "deleteduser_delete"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      responses:
        204:
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /deletedusersite:
    get:
      tags:
      - "user_data"
      operationId: "deletedusersite_list"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "An optional query parameter specifying the offset in the result\
          \ set to start from."
        required: false
        type: "integer"
        default: 0
        minimum: 0
      - name: "limit"
        in: "query"
        description: "An optional query parameter to limit the number of results returned."
        required: false
        type: "integer"
        default: 20
        maximum: 100
        minimum: 1
      - name: "user_id"
        in: "query"
        description: "An optional query parameter to filter by user_id"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/deleted_user_site"
          headers:
            X-Total-Count:
              type: "integer"
              description: "The total number of results matching the query"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    post:
      tags:
      - "user_data"
      operationId: "deletedusersite_create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/deleted_user_site_create"
      responses:
        201:
          description: ""
          schema:
            $ref: "#/definitions/deleted_user_site"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
  /deletedusersite/{user_id}/{site_id}:
    get:
      tags:
      - "user_data"
      operationId: "deletedusersite_read"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/deleted_user_site"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    put:
      tags:
      - "user_data"
      operationId: "deletedusersite_update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/deleted_user_site_update"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/deleted_user_site"
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
    delete:
      tags:
      - "user_data"
      operationId: "deletedusersite_delete"
      parameters:
      - name: "user_id"
        in: "path"
        description: "A UUID value identifying the user."
        required: true
        type: "string"
        format: "uuid"
      - name: "site_id"
        in: "path"
        description: "A unique integer value identifying the site."
        required: true
        type: "integer"
      responses:
        204:
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.user_data_controller"
securityDefinitions:
  APIKeyHeader:
    type: "apiKey"
    name: "X-API-Key"
    in: "header"
definitions:
  admin_note:
    type: "object"
    required:
    - "created_at"
    - "creator_id"
    - "id"
    - "note"
    - "updated_at"
    - "user_id"
    properties:
      id:
        type: "integer"
        readOnly: true
      user_id:
        type: "string"
        format: "uuid"
      creator_id:
        type: "string"
        format: "uuid"
      note:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
        readOnly: true
      updated_at:
        type: "string"
        format: "date-time"
        readOnly: true
    example:
      note: "note"
      updated_at: "2000-01-23T04:56:07.000+00:00"
      user_id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      creator_id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      created_at: "2000-01-23T04:56:07.000+00:00"
      id: 0
  admin_note_create:
    type: "object"
    required:
    - "creator_id"
    - "note"
    - "user_id"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      creator_id:
        type: "string"
        format: "uuid"
      note:
        type: "string"
  admin_note_update:
    type: "object"
    properties:
      note:
        type: "string"
  site_data_schema:
    type: "object"
    required:
    - "created_at"
    - "schema"
    - "site_id"
    - "updated_at"
    properties:
      site_id:
        type: "integer"
      schema:
        type: "object"
        properties: {}
      created_at:
        type: "string"
        format: "date-time"
        readOnly: true
      updated_at:
        type: "string"
        format: "date-time"
        readOnly: true
    example:
      schema: "{}"
      updated_at: "2000-01-23T04:56:07.000+00:00"
      site_id: 0
      created_at: "2000-01-23T04:56:07.000+00:00"
  site_data_schema_create:
    type: "object"
    required:
    - "schema"
    - "site_id"
    properties:
      site_id:
        type: "integer"
      schema:
        type: "object"
        properties: {}
  site_data_schema_update:
    type: "object"
    properties:
      schema:
        type: "object"
        properties: {}
  user_site_data:
    type: "object"
    required:
    - "created_at"
    - "data"
    - "site_id"
    - "updated_at"
    - "user_id"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      site_id:
        type: "integer"
      data:
        type: "object"
        properties: {}
      created_at:
        type: "string"
        format: "date-time"
        readOnly: true
      updated_at:
        type: "string"
        format: "date-time"
        readOnly: true
    example:
      data: "{}"
      updated_at: "2000-01-23T04:56:07.000+00:00"
      user_id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      site_id: 0
      created_at: "2000-01-23T04:56:07.000+00:00"
  user_site_data_create:
    type: "object"
    required:
    - "data"
    - "site_id"
    - "user_id"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      site_id:
        type: "integer"
      data:
        type: "object"
        properties: {}
  user_site_data_update:
    type: "object"
    properties:
      data:
        type: "object"
        properties: {}
  health_info:
    type: "object"
    required:
    - "db_timestamp"
    - "host"
    - "server_timestamp"
    - "version"
    properties:
      host:
        type: "string"
      server_timestamp:
        type: "string"
        format: "date-time"
      version:
        type: "string"
      db_timestamp:
        type: "string"
        format: "date-time"
    description: "Health check response"
    example:
      server_timestamp: "2000-01-23T04:56:07.000+00:00"
      host: "host"
      version: "version"
      db_timestamp: "2000-01-23T04:56:07.000+00:00"
  deleted_user:
    type: "object"
    required:
    - "created_at"
    - "deleter_id"
    - "id"
    - "reason"
    - "updated_at"
    - "username"
    properties:
      id:
        type: "string"
        format: "uuid"
      username:
        type: "string"
      email:
        type: "string"
        format: "email"
      msisdn:
        type: "string"
      reason:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
        readOnly: true
      updated_at:
        type: "string"
        format: "date-time"
        readOnly: true
      deleted_at:
        type: "string"
        format: "date-time"
      deleter_id:
        type: "string"
        format: "uuid"
    example:
      reason: "reason"
      updated_at: "2000-01-23T04:56:07.000+00:00"
      created_at: "2000-01-23T04:56:07.000+00:00"
      deleter_id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      msisdn: "msisdn"
      deleted_at: "2000-01-23T04:56:07.000+00:00"
      email: "email"
      username: "username"
  deleted_user_create:
    type: "object"
    required:
    - "deleter_id"
    - "id"
    - "reason"
    - "username"
    properties:
      id:
        type: "string"
        format: "uuid"
      username:
        type: "string"
      email:
        type: "string"
        format: "email"
      msisdn:
        type: "string"
      reason:
        type: "string"
      deleter_id:
        type: "string"
        format: "uuid"
  deleted_user_update:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"
        format: "email"
      msisdn:
        type: "string"
      reason:
        type: "string"
      deleted_at:
        type: "string"
        format: "date-time"
      deleter_id:
        type: "string"
        format: "uuid"
  deleted_user_site:
    type: "object"
    required:
    - "created_at"
    - "deleted_user_id"
    - "site_id"
    - "updated_at"
    properties:
      deleted_user_id:
        type: "string"
        format: "uuid"
      site_id:
        type: "integer"
      created_at:
        type: "string"
        format: "date-time"
        readOnly: true
      updated_at:
        type: "string"
        format: "date-time"
        readOnly: true
      deletion_requested_at:
        type: "string"
        format: "date-time"
      deletion_requested_via:
        type: "string"
      deletion_confirmed_at:
        type: "string"
        format: "date-time"
      deletion_confirmed_via:
        type: "string"
    example:
      deletion_confirmed_at: "2000-01-23T04:56:07.000+00:00"
      updated_at: "2000-01-23T04:56:07.000+00:00"
      deletion_requested_at: "2000-01-23T04:56:07.000+00:00"
      site_id: 0
      deletion_requested_via: "deletion_requested_via"
      created_at: "2000-01-23T04:56:07.000+00:00"
      deleted_user_id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      deletion_confirmed_via: "deletion_confirmed_via"
  deleted_user_site_create:
    type: "object"
    required:
    - "deleted_user_id"
    - "site_id"
    properties:
      deleted_user_id:
        type: "string"
        format: "uuid"
      site_id:
        type: "integer"
      deletion_requested_at:
        type: "string"
        format: "date-time"
      deletion_requested_via:
        type: "string"
      deletion_confirmed_at:
        type: "string"
        format: "date-time"
      deletion_confirmed_via:
        type: "string"
  deleted_user_site_update:
    type: "object"
    properties:
      deletion_requested_at:
        type: "string"
        format: "date-time"
      deletion_requested_via:
        type: "string"
      deletion_confirmed_at:
        type: "string"
        format: "date-time"
      deletion_confirmed_via:
        type: "string"
parameters:
  optional_limit:
    name: "limit"
    in: "query"
    description: "An optional query parameter to limit the number of results returned."
    required: false
    type: "integer"
    default: 20
    maximum: 100
    minimum: 1
  optional_offset:
    name: "offset"
    in: "query"
    description: "An optional query parameter specifying the offset in the result\
      \ set to start from."
    required: false
    type: "integer"
    default: 0
    minimum: 0
  optional_site_filter:
    name: "site_id"
    in: "query"
    description: "An optional query parameter to filter by site_id"
    required: false
    type: "integer"
  optional_user_filter:
    name: "user_id"
    in: "query"
    description: "An optional query parameter to filter by user_id"
    required: false
    type: "string"
    format: "uuid"
  admin_note_id:
    name: "admin_note_id"
    in: "path"
    description: "A unique integer value identifying the admin note."
    required: true
    type: "integer"
  site_id:
    name: "site_id"
    in: "path"
    description: "A unique integer value identifying the site."
    required: true
    type: "integer"
  user_id:
    name: "user_id"
    in: "path"
    description: "A UUID value identifying the user."
    required: true
    type: "string"
    format: "uuid"
  optional_deleter_id_filter:
    name: "deleter_id"
    in: "query"
    description: "An optional query parameter to filter by deleter_id"
    required: false
    type: "string"
    format: "uuid"
